name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Install percy 
      run:  |
        npm install --save-dev @percy/cli
        npx percy snapshot public/
      env:
        PERCY_TOKEN: $

    - name: Run Cypress tests with percy
      run: npm run percy
